export { SCHEMA_VERSION, type ParseResult } from "./common.js";
export {
  PROJECT_SCHEMA_URL,
  MIN_SNAP_WINDOW_S,
  MAX_SNAP_WINDOW_S,
  ProjectConfigSchema,
  type ProjectConfig,
  parseProjectConfig,
  createProjectConfig,
} from "./project.js";
export {
  TIMELINE_SCHEMA_URL,
  CORE_CLIP_TYPES,
  ADAPTER_CLIP_TYPE_PATTERN,
  TimelineSchema,
  TrackSchema,
  ClipTrackSchema,
  SubtitleTrackSchema,
  ClipSchema,
  MediaClipSchema,
  TimelineClipSchema,
  AdapterClipSchema,
  TransformSchema,
  ClipAudioSchema,
  type Timeline,
  type Track,
  type ClipTrack,
  type SubtitleTrack,
  type Clip,
  type MediaClip,
  type TimelineClip,
  type AdapterClip,
  type Transform,
  type ClipAudio,
  parseTimeline,
  createTimeline,
} from "./timeline.js";
export { generateJsonSchemas } from "./json-schema.js";
export {
  PLUGIN_MANIFEST_FILE,
  PLUGIN_MANIFEST_SCHEMA_URL,
  BUILTIN_COMMANDS,
  PluginNameSchema,
  PluginManifestSchema,
  type PluginManifest,
  parsePluginManifest,
  ExportPresetSchema,
  type ExportPreset,
  parseExportPreset,
} from "./plugin.js";
export {
  TRANSCRIPT_SCHEMA_URL,
  TranscriptSchema,
  type Transcript,
  type TranscriptFileWord,
  WordIdSchema,
  wordIdNumber,
  parseTranscript,
} from "./transcript.js";
export {
  ScriptSceneSchema,
  ScriptMetaSchema,
  type ScriptScene,
  type ScriptMeta,
  type ScriptOutline,
  isScriptPath,
  parseScript,
  scriptRefPathProblem,
  scriptSlug,
  splitScriptRef,
} from "./script.js";
export {
  IDENTITY_PLACEMENT,
  type Placement,
  type Size,
  type LayerRect,
  type NestedTimelines,
  placementOf,
  isIdentityPlacement,
  layerRect,
  composePlacement,
  flattenTimeline,
} from "./composite.js";
export {
  SUBTITLE_FONT,
  SUBTITLE_POSITIONS,
  SUBTITLE_PRESETS,
  SUBTITLE_PRESET_IDS,
  DEFAULT_SUBTITLE_PRESET,
  type SubtitlePosition,
  type SubtitlePreset,
  type SubtitlePresetId,
  type SubtitleStyle,
  type SubtitleWord,
  type SubtitleCue,
  type SubtitleLayout,
  type ResolvedSubtitleTrack,
  type TranscriptLookup,
  resolveSubtitleStyle,
  subtitleWords,
  subtitleCues,
  subtitleAt,
  subtitleLayout,
  subtitleTracks,
} from "./subtitles.js";
